// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUohzxQdKlLUSnM7CWm83rWKCO2AUW3_o',
    appId: '1:303868688064:android:f9c36acf53e15bdd745f25',
    messagingSenderId: '303868688064',
    projectId: 'sign-up-app-227a0',
    storageBucket: 'sign-up-app-227a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRQjV7AbkP5FRwRivt-BXN0yIQTJagURk',
    appId: '1:303868688064:ios:49225ac945cf69b5745f25',
    messagingSenderId: '303868688064',
    projectId: 'sign-up-app-227a0',
    storageBucket: 'sign-up-app-227a0.firebasestorage.app',
    iosBundleId: 'com.example.signUp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRQjV7AbkP5FRwRivt-BXN0yIQTJagURk',
    appId: '1:303868688064:ios:49225ac945cf69b5745f25',
    messagingSenderId: '303868688064',
    projectId: 'sign-up-app-227a0',
    storageBucket: 'sign-up-app-227a0.firebasestorage.app',
    iosBundleId: 'com.example.signUp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjd8eiCDbwt9Qb2qEPdCyE_dWoOLYtlfY',
    appId: '1:303868688064:web:1221b9c40981978f745f25',
    messagingSenderId: '303868688064',
    projectId: 'sign-up-app-227a0',
    authDomain: 'sign-up-app-227a0.firebaseapp.com',
    storageBucket: 'sign-up-app-227a0.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjd8eiCDbwt9Qb2qEPdCyE_dWoOLYtlfY',
    appId: '1:303868688064:web:1221b9c40981978f745f25',
    messagingSenderId: '303868688064',
    projectId: 'sign-up-app-227a0',
    authDomain: 'sign-up-app-227a0.firebaseapp.com',
    storageBucket: 'sign-up-app-227a0.firebasestorage.app',
  );

}